package model

enum class WorkerDayType {
    MONDAY_NIGHT,
    MONDAY_MORNING,
    MONDAY_AFTERNOON,

    TUESDAY_NIGHT,
    TUESDAY_MORNING,
    TUESDAY_AFTERNOON,

    WEDNESDAY_NIGHT,
    WEDNESDAY_MORNING,
    WEDNESDAY_AFTERNOON,

    THURSDAY_NIGHT,
    THURSDAY_MORNING,
    THURSDAY_AFTERNOON,

    FRIDAY_NIGHT,
    FRIDAY_MORNING,
    FRIDAY_AFTERNOON,

    SATURDAY_NIGHT,
    SATURDAY_MORNING,
    SATURDAY_AFTERNOON,

    SUNDAY_NIGHT,
    SUNDAY_MORNING,
    SUNDAY_AFTERNOON
}
